easy_phrases = [
    "Hello, nice to meet you!",
    "I enjoy sunny days.",
    "What's your favorite food?",
    "Do you have any hobbies?",
    "I like playing games.",
    "How's your day going?",
    "I have a pet cat.",
    "Do you like to read?",
    "What's your favorite color?",
    "I like watching movies.",
    "Have you traveled much?",
    "What's your dream job?",
    "I enjoy listening to music.",
    "Do you have any siblings?",
    "Let's grab a coffee sometime.",
    "I love nature walks.",
    "What's your favorite season?",
    "I like taking photos.",
    "Pizza or pasta?",
    "I enjoy simple pleasures.",
    "What's your morning routine?",
    "I like to learn new things.",
    "Any weekend plans?",
    "I like to laugh a lot.",
    "Favorite childhood game?",
]

medium_phrases = [
    "The quick brown fox jumps over the lazy dog.",
    "Learning a new language is a fun challenge.",
    "My favorite hobby is programming.",
    "Let's have a cup of coffee.",
    "I can introduce myself in English.",
    "Have you traveled to other countries?",
    "I'm planning to attend a coding meetup soon.",
    "Let's meet for coffee and chat.",
    "The sun sets behind the mountains.",
    "I recently picked up painting as a hobby.",
    "Coffee or tea? What's your preference?",
    "I enjoy exploring new cuisines.",
    "Have you ever tried rock climbing?",
    "I'm planning a weekend getaway.",
    "What's your take on mindfulness meditation?",
    "I love attending outdoor music festivals.",
    "Do you have a favorite quote or saying?",
    "I find architecture and design intriguing.",
    "Let's plan a picnic in the park.",
    "I like to discuss philosophy with friends.",
    "What's the most beautiful place you've visited?",
    "I'm fascinated by ancient history.",
    "Do you have a favorite podcast?",
    "I enjoy building things with my hands.",
    "Have you ever attended a live theater performance?",
    "Let's try cooking a new recipe together.",
    "I find stargazing on clear nights calming.",
    "What's your opinion on virtual reality?",
    "I'm planning to start a book club.",
    "Do you like attending art exhibitions?",
    "I appreciate a good sense of humor.",
    "Let's plan a day at the amusement park.",
    "What's your favorite way to spend a lazy Sunday?",
    "I'm considering taking up a dance class.",
]

hard_phrases = [
    "Ubiquitous serendipity illuminates the human experience.",
    "Ineffable beauty lies within the simplicity of existence.",
    "Nebulous thoughts coalesce into profound insights.",
    "Tranquil rivers weave through the tapestry of nature.",
    "Ephemeral moments crystallize into everlasting memories.",
    "Metamorphosing challenges sculpt the essence of character.",
    "Peregrination unveils the hidden gems of the world.",
    "In the crucible of adversity, resilience is forged.",
    "Arcane knowledge fuels the fires of innovation.",
    "Cacophony dissipates in the presence of mindful silence.",
    "Ambivalence navigates the delicate balance of decisions.",
    "A symphony of ideas orchestrates the creative process.",
    "The quintessence of empathy transcends societal boundaries.",
    "Profound questions echo in the corridors of contemplation.",
    "Abyssal depths of curiosity yield treasures of understanding.",
    "The perennial quest for knowledge is a noble pursuit.",
    "Divergent paths converge in the mosaic of destiny.",
    "Metacognition unveils the labyrinth of self-awareness.",
    "In the crucible of time, legacies are forged.",
    "Surreptitious whispers unveil the secrets of the cosmos.",
    "Epistemological endeavors enrich the human intellect.",
    "Symbiotic relationships harmonize the rhythm of life.",
    "Esoteric wisdom emanates from the ancient scrolls of philosophy.",
    "In the cauldron of innovation, ideas undergo alchemy.",
    "The kaleidoscope of existence refracts myriad perspectives.",
    "Philosophical discourse is the crucible of intellectual refinement.",
]